"""
report.py — Generate professional PDF security reports with ReportLab.

This is a Enrich-only feature, gated before this module is imported.

Why ReportLab?
  Most established Python PDF library. Full control over layout.
  Used in professional reporting tools, courts, healthcare — it's battle-tested.

The safe_text() function is critical:
  ReportLab Paragraph widgets treat content as XML. This means any text
  containing <, >, or & will crash ReportLab with an XML parse error.
  Security tool output is full of these characters:
    - Shell commands:      nmap -p <port>
    - Metasploit prompts:  msf6 > use exploit/...
    - CVE descriptions:    version < 2.4.50
    - HTML in server headers
  Every string that goes into a Paragraph MUST be sanitized with safe_text().

Structure of the generated PDF:
  Page 1: Cover — tool name, date, target count, overall risk level
  Page 2+: Executive summary table — one row per finding
  Page N+: Detailed findings — one section per finding with full AI analysis
"""

from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
)


# ---------------------------------------------------------------------------
# Text sanitization — must be applied to ALL strings before Paragraph()
# ---------------------------------------------------------------------------

def safe_text(text: str) -> str:
    """
    Escape characters that would break ReportLab's XML parser.

    Always call this on any user-derived or AI-generated string before
    passing it to Paragraph(). Missing even one call will crash PDF generation.

    Why the order matters:
      Replace & first. If you replace < first and then &,
      you'd double-escape things like &lt; → &amp;lt;
    """
    if not text:
        return ""
    text = str(text)
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text


# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------

PRIORITY_COLORS = {
    "critical": colors.HexColor("#c0392b"),  # dark red
    "high":     colors.HexColor("#e67e22"),  # orange
    "medium":   colors.HexColor("#f39c12"),  # yellow-orange
    "low":      colors.HexColor("#27ae60"),  # green
    None:       colors.HexColor("#7f8c8d"),  # grey
    "unrated":  colors.HexColor("#7f8c8d"),
}

VULNMIND_BLUE = colors.HexColor("#2c3e50")
LIGHT_GREY = colors.HexColor("#ecf0f1")


# ---------------------------------------------------------------------------
# Main PDF generation function
# ---------------------------------------------------------------------------

def generate_pdf(findings: list, output_path: str) -> None:
    """
    Generate a professional PDF security report.

    Args:
        findings: List of Finding objects (should be AI-enriched)
        output_path: Where to write the PDF file

    The report structure:
      - Cover page
      - Executive summary table
      - Per-finding detail pages
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = _build_styles()
    story = []

    # Cover page
    story.extend(_build_cover(findings, styles))
    story.append(PageBreak())

    # Executive summary table
    story.extend(_build_summary_table(findings, styles))
    story.append(PageBreak())

    # Per-finding detail sections
    for i, finding in enumerate(findings):
        story.extend(_build_finding_section(finding, styles))
        if i < len(findings) - 1:
            story.append(PageBreak())

    doc.build(story)


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------

def _build_cover(findings: list, styles: dict) -> list:
    """Build the cover page content."""
    elements = []

    elements.append(Spacer(1, 1.5 * inch))

    # Title
    elements.append(Paragraph("Security Assessment Report", styles["title"]))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph("Generated by VulnMind", styles["subtitle"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="100%", thickness=2, color=VULNMIND_BLUE))
    elements.append(Spacer(1, 0.5 * inch))

    # Stats
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    critical = sum(1 for f in findings if f.priority == "critical")
    high = sum(1 for f in findings if f.priority == "high")
    medium = sum(1 for f in findings if f.priority == "medium")
    low = sum(1 for f in findings if f.priority == "low")

    # Determine overall risk
    if critical > 0:
        overall_risk = "CRITICAL"
        risk_color = PRIORITY_COLORS["critical"]
    elif high > 0:
        overall_risk = "HIGH"
        risk_color = PRIORITY_COLORS["high"]
    elif medium > 0:
        overall_risk = "MEDIUM"
        risk_color = PRIORITY_COLORS["medium"]
    else:
        overall_risk = "LOW"
        risk_color = PRIORITY_COLORS["low"]

    elements.append(Paragraph(f"Overall Risk: {overall_risk}", styles["risk"]))
    elements.append(Spacer(1, 0.5 * inch))

    # Summary stats table
    stat_data = [
        ["Total Findings", "Critical", "High", "Medium", "Low"],
        [str(len(findings)), str(critical), str(high), str(medium), str(low)],
    ]
    stat_table = Table(stat_data, colWidths=[1.5 * inch] * 5)
    stat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), VULNMIND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (1, 1), (1, 1), PRIORITY_COLORS["critical"]),
        ("BACKGROUND", (2, 1), (2, 1), PRIORITY_COLORS["high"]),
        ("BACKGROUND", (3, 1), (3, 1), PRIORITY_COLORS["medium"]),
        ("BACKGROUND", (4, 1), (4, 1), PRIORITY_COLORS["low"]),
        ("TEXTCOLOR", (1, 1), (-1, 1), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, 1), 18),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 1, colors.grey),
    ]))
    elements.append(stat_table)

    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph(f"Report Date: {safe_text(now)}", styles["meta"]))

    return elements


def _build_summary_table(findings: list, styles: dict) -> list:
    """Build the executive summary table — one row per finding."""
    elements = []
    elements.append(Paragraph("Executive Summary", styles["h1"]))
    elements.append(Spacer(1, 0.2 * inch))

    # Table header
    header = ["#", "Host", "Port", "Finding", "Priority"]
    data = [header]

    for i, finding in enumerate(findings, 1):
        priority = finding.priority or "unrated"
        title = finding.title[:55] + "…" if len(finding.title) > 55 else finding.title
        data.append([
            str(i),
            safe_text(finding.host),
            str(finding.port) if finding.port else "-",
            # Use Paragraph for the title cell so long text wraps
            Paragraph(safe_text(title), styles["table_body"]),
            safe_text(priority.upper()),
        ])

    col_widths = [0.4 * inch, 1.4 * inch, 0.6 * inch, 3.8 * inch, 0.8 * inch]
    table = Table(data, colWidths=col_widths, repeatRows=1)

    # Build per-row priority colour styling
    row_styles = [
        ("BACKGROUND", (0, 0), (-1, 0), VULNMIND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
        ("ALIGN", (4, 0), (4, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]

    for i, finding in enumerate(findings, 1):
        p = finding.priority or None
        p_color = PRIORITY_COLORS.get(p, PRIORITY_COLORS[None])
        # Colour the priority cell
        row_styles.append(("BACKGROUND", (4, i), (4, i), p_color))
        row_styles.append(("TEXTCOLOR", (4, i), (4, i), colors.white))
        row_styles.append(("FONTNAME", (4, i), (4, i), "Helvetica-Bold"))

    table.setStyle(TableStyle(row_styles))
    elements.append(table)

    return elements


def _build_finding_section(finding, styles: dict) -> list:
    """Build the detailed section for one finding."""
    elements = []

    priority = finding.priority or "unrated"
    p_color = PRIORITY_COLORS.get(finding.priority, PRIORITY_COLORS[None])

    # Section header
    elements.append(Paragraph(safe_text(finding.title), styles["h1"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=p_color))
    elements.append(Spacer(1, 0.1 * inch))

    # Metadata row
    port_str = f":{finding.port}" if finding.port else ""
    meta_parts = [
        f"Host: {finding.host}{port_str}",
        f"Service: {finding.service or 'unknown'}",
        f"Tool: {finding.source_tool}",
        f"Priority: {priority.upper()}",
    ]
    if finding.cve_ids:
        meta_parts.append(f"CVEs: {', '.join(finding.cve_ids)}")

    for part in meta_parts:
        elements.append(Paragraph(safe_text(part), styles["meta_field"]))
    elements.append(Spacer(1, 0.15 * inch))

    # AI Explanation
    if finding.ai_explanation:
        elements.append(Paragraph("Analysis", styles["h2"]))
        elements.append(Paragraph(safe_text(finding.ai_explanation), styles["body"]))
        elements.append(Spacer(1, 0.15 * inch))
    elif finding.description:
        elements.append(Paragraph("Description", styles["h2"]))
        elements.append(Paragraph(safe_text(finding.description), styles["body"]))
        elements.append(Spacer(1, 0.15 * inch))

    # Suggested commands
    if finding.suggested_commands:
        elements.append(Paragraph("Recommended Commands", styles["h2"]))
        for cmd in finding.suggested_commands:
            # Use Paragraph (not plain string) so long commands wrap properly
            elements.append(Paragraph(
                f"$ {safe_text(cmd)}", styles["code"]
            ))
        elements.append(Spacer(1, 0.15 * inch))

    # Metasploit modules
    if finding.metasploit_modules:
        elements.append(Paragraph("Metasploit Modules", styles["h2"]))
        for mod in finding.metasploit_modules:
            elements.append(Paragraph(
                f"use {safe_text(mod)}", styles["code"]
            ))
        elements.append(Spacer(1, 0.15 * inch))

    # False positive note
    if finding.false_positive_likelihood in ("medium", "high"):
        elements.append(Paragraph("False Positive Note", styles["h2"]))
        fp_text = f"Likelihood: {finding.false_positive_likelihood}"
        if finding.false_positive_reason:
            fp_text += f" — {finding.false_positive_reason}"
        elements.append(Paragraph(safe_text(fp_text), styles["body"]))

    # Evidence
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph("Raw Evidence", styles["h2"]))
    evidence = finding.raw_evidence[:600] + ("…" if len(finding.raw_evidence) > 600 else "")
    elements.append(Paragraph(safe_text(evidence), styles["evidence"]))

    return elements


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def _build_styles() -> dict:
    """Build a dict of ReportLab ParagraphStyles for the report."""
    base = getSampleStyleSheet()

    return {
        "title": ParagraphStyle(
            "VTitle",
            parent=base["Title"],
            fontSize=28,
            textColor=VULNMIND_BLUE,
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "VSubtitle",
            parent=base["Normal"],
            fontSize=14,
            textColor=colors.grey,
            spaceAfter=12,
        ),
        "risk": ParagraphStyle(
            "VRisk",
            parent=base["Normal"],
            fontSize=22,
            textColor=VULNMIND_BLUE,
            fontName="Helvetica-Bold",
            alignment=1,  # center
        ),
        "meta": ParagraphStyle(
            "VMeta",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.grey,
            alignment=1,  # center
        ),
        "meta_field": ParagraphStyle(
            "VMetaField",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=2,
        ),
        "h1": ParagraphStyle(
            "VH1",
            parent=base["Heading1"],
            fontSize=14,
            textColor=VULNMIND_BLUE,
            spaceAfter=4,
        ),
        "h2": ParagraphStyle(
            "VH2",
            parent=base["Heading2"],
            fontSize=11,
            textColor=VULNMIND_BLUE,
            spaceBefore=6,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "VBody",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            spaceAfter=6,
        ),
        "code": ParagraphStyle(
            "VCode",
            parent=base["Code"],
            fontSize=8,
            fontName="Courier",
            backColor=LIGHT_GREY,
            leftIndent=6,
            spaceAfter=3,
        ),
        "evidence": ParagraphStyle(
            "VEvidence",
            parent=base["Code"],
            fontSize=7,
            fontName="Courier",
            backColor=LIGHT_GREY,
            leftIndent=6,
            textColor=colors.HexColor("#555555"),
        ),
        "table_body": ParagraphStyle(
            "VTableBody",
            parent=base["Normal"],
            fontSize=9,
        ),
    }
